# Backend/app/routers/documents.py

import json
from fastapi import APIRouter, HTTPException, Depends, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Any, List
from sqlalchemy.orm import Session
from io import BytesIO
import datetime

from app.deps import get_db
from app.routers.auth import get_current_user   # ✅ auth is in auth.py
from app import models
from app.utils.pdf_generator import generate_document, PDF_GENERATORS

router = APIRouter(prefix="/documents", tags=["Documents"])


# ─── Schemas ───────────────────────────────────────────────────────────────────

class GenerateDocumentRequest(BaseModel):
    template_type: str
    form_data: dict[str, Any]


class GenerateDocumentResponse(BaseModel):
    document_id: int
    template_type: str
    title: str
    message: str
    created_at: str


class DocumentListItem(BaseModel):
    document_id: int
    title: str
    type: str
    created_at: str

    class Config:
        from_attributes = True


# ─── Routes ────────────────────────────────────────────────────────────────────

@router.get("/templates")
def list_templates():
    """Return list of supported template types"""
    return {
        "templates": list(PDF_GENERATORS.keys()),
        "count": len(PDF_GENERATORS)
    }


@router.post("/generate", response_model=GenerateDocumentResponse)
def generate_document_endpoint(
    request: GenerateDocumentRequest,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),   # ✅ must be logged in
):
    """Generate a PDF, save to DB under the logged-in user, return doc_id"""

    if request.template_type not in PDF_GENERATORS:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unknown template type '{request.template_type}'. "
                   f"Valid: {', '.join(PDF_GENERATORS.keys())}"
        )

    # Generate PDF bytes
    try:
        pdf_bytes = generate_document(request.template_type, request.form_data)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"PDF generation failed: {str(e)}"
        )

    # Build a readable title
    title_map = {
        "fir":          "FIR (First Information Report)",
        "tenancy":      "Tenancy Agreement",
        "divorce":      "Divorce Notice (Talaq)",
        "affidavit":    "Affidavit",
        "poa":          "Power of Attorney",
        "legal_notice": "Legal Notice",
    }
    doc_title = (
        f"{title_map.get(request.template_type, request.template_type)} — "
        f"{datetime.date.today().strftime('%d %b %Y')}"
    )

    # Save to existing Document model in DB
    db_doc = models.Document(
        user_id=current_user.user_id,           # ✅ linked to logged-in user
        template_id=None,
        title=doc_title,
        type=request.template_type,
        content=json.dumps(request.form_data),  # form data as JSON string
        pdf_data=pdf_bytes,                      # ✅ PDF bytes stored
    )
    db.add(db_doc)
    db.commit()
    db.refresh(db_doc)

    return GenerateDocumentResponse(
        document_id=db_doc.doc_id,
        template_type=request.template_type,
        title=doc_title,
        message="Document generated and saved successfully",
        created_at=db_doc.created_at.isoformat(),
    )


@router.get("/my-documents", response_model=List[DocumentListItem])
def get_my_documents(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Get all documents generated by the logged-in user"""

    docs = db.query(models.Document).filter(
        models.Document.user_id == current_user.user_id
    ).order_by(models.Document.created_at.desc()).all()

    return [
        DocumentListItem(
            document_id=d.doc_id,
            title=d.title,
            type=d.type,
            created_at=d.created_at.isoformat(),
        )
        for d in docs
    ]


@router.get("/download/{document_id}")
def download_document(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),  # ✅ must be logged in
):
    """Download PDF — only the owner can download their document"""

    db_doc = db.query(models.Document).filter(
        models.Document.doc_id == document_id
    ).first()

    if not db_doc:
        raise HTTPException(status_code=404, detail="Document not found")

    # ✅ Ownership check
    if db_doc.user_id != current_user.user_id:
        raise HTTPException(status_code=403, detail="Access denied")

    if not db_doc.pdf_data:
        raise HTTPException(status_code=404, detail="PDF data not found")

    filename = f"{db_doc.type}_{db_doc.doc_id}.pdf"

    return StreamingResponse(
        BytesIO(db_doc.pdf_data),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Content-Length": str(len(db_doc.pdf_data)),
        }
    )


@router.delete("/delete/{document_id}")
def delete_document(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Delete a document — only the owner can delete"""

    db_doc = db.query(models.Document).filter(
        models.Document.doc_id == document_id
    ).first()

    if not db_doc:
        raise HTTPException(status_code=404, detail="Document not found")

    if db_doc.user_id != current_user.user_id:
        raise HTTPException(status_code=403, detail="Access denied")

    db.delete(db_doc)
    db.commit()

    return {"message": "Document deleted successfully"}